---
#example plybook
- name: Gather serial number and MAC address from Cisco IOS-XE switches
  hosts: ios_xe_switches
  gather_facts: yes
  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: ios_facts

    - name: Print all gathered facts
      debug:
        var: ios_facts

    - name: Print serial number and MAC address
      debug:
        msg:
          - "Serial Number: {{ ios_facts.ansible_facts.ansible_net_serialnum }}"
          - "MAC Address: {{ ios_facts.ansible_facts.ansible_net_macaddress }}"
